// @generated by packages/design-tokens (Style Dictionary). Do not edit.
// Regenerate with `pnpm nx build @gitraptor/tokens`; CI fails if this file is stale.

use crate::{Ansi16, Attrs, ColorSpec, Rgb, Role, SymbolSpec, Values};

/// A semantic color token (DSYS-GRP-001 § 2.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum ColorToken {
    /// `text.default`
    TextDefault,
    /// `text.muted`
    TextMuted,
    /// `text.inverse`
    TextInverse,
    /// `bg.default`
    BgDefault,
    /// `bg.selected`
    BgSelected,
    /// `bg.highlight`
    BgHighlight,
    /// `accent.default`
    AccentDefault,
    /// `focus.default`
    FocusDefault,
    /// `status.success`
    StatusSuccess,
    /// `status.warning`
    StatusWarning,
    /// `status.danger`
    StatusDanger,
    /// `status.info`
    StatusInfo,
    /// `git.added`
    GitAdded,
    /// `git.removed`
    GitRemoved,
    /// `git.modified`
    GitModified,
    /// `git.conflict`
    GitConflict,
    /// `git.branch.base`
    GitBranchBase,
    /// `agent.1`
    Agent1,
    /// `agent.2`
    Agent2,
    /// `agent.3`
    Agent3,
    /// `agent.4`
    Agent4,
    /// `agent.5`
    Agent5,
    /// `agent.6`
    Agent6,
    /// `agent.7`
    Agent7,
    /// `agent.8`
    Agent8,
    /// `agent.state.active`: Agent active: alias of status.success; the symbol is the primary signal
    AgentStateActive,
    /// `agent.state.idle`: Agent idle: alias of text.muted
    AgentStateIdle,
    /// `agent.state.done`: Agent finished: alias of text.muted
    AgentStateDone,
}

impl ColorToken {
    /// Every token, in declaration order.
    pub const ALL: [ColorToken; 28] = [
        ColorToken::TextDefault,
        ColorToken::TextMuted,
        ColorToken::TextInverse,
        ColorToken::BgDefault,
        ColorToken::BgSelected,
        ColorToken::BgHighlight,
        ColorToken::AccentDefault,
        ColorToken::FocusDefault,
        ColorToken::StatusSuccess,
        ColorToken::StatusWarning,
        ColorToken::StatusDanger,
        ColorToken::StatusInfo,
        ColorToken::GitAdded,
        ColorToken::GitRemoved,
        ColorToken::GitModified,
        ColorToken::GitConflict,
        ColorToken::GitBranchBase,
        ColorToken::Agent1,
        ColorToken::Agent2,
        ColorToken::Agent3,
        ColorToken::Agent4,
        ColorToken::Agent5,
        ColorToken::Agent6,
        ColorToken::Agent7,
        ColorToken::Agent8,
        ColorToken::AgentStateActive,
        ColorToken::AgentStateIdle,
        ColorToken::AgentStateDone,
    ];

    /// The token name in `packages/design-tokens`.
    pub const fn name(self) -> &'static str {
        match self {
            ColorToken::TextDefault => "text.default",
            ColorToken::TextMuted => "text.muted",
            ColorToken::TextInverse => "text.inverse",
            ColorToken::BgDefault => "bg.default",
            ColorToken::BgSelected => "bg.selected",
            ColorToken::BgHighlight => "bg.highlight",
            ColorToken::AccentDefault => "accent.default",
            ColorToken::FocusDefault => "focus.default",
            ColorToken::StatusSuccess => "status.success",
            ColorToken::StatusWarning => "status.warning",
            ColorToken::StatusDanger => "status.danger",
            ColorToken::StatusInfo => "status.info",
            ColorToken::GitAdded => "git.added",
            ColorToken::GitRemoved => "git.removed",
            ColorToken::GitModified => "git.modified",
            ColorToken::GitConflict => "git.conflict",
            ColorToken::GitBranchBase => "git.branch.base",
            ColorToken::Agent1 => "agent.1",
            ColorToken::Agent2 => "agent.2",
            ColorToken::Agent3 => "agent.3",
            ColorToken::Agent4 => "agent.4",
            ColorToken::Agent5 => "agent.5",
            ColorToken::Agent6 => "agent.6",
            ColorToken::Agent7 => "agent.7",
            ColorToken::Agent8 => "agent.8",
            ColorToken::AgentStateActive => "agent.state.active",
            ColorToken::AgentStateIdle => "agent.state.idle",
            ColorToken::AgentStateDone => "agent.state.done",
        }
    }

    pub(crate) const fn spec(self) -> &'static ColorSpec {
        &COLOR_SPECS[self as usize]
    }
}

const COLOR_SPECS: [ColorSpec; 28] = [
    // text.default
    ColorSpec {
        role: Role::Foreground,
        inherit: true,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(228, 228, 228), ansi256: 254, ansi256_rgb: Rgb(228, 228, 228), ansi16: Ansi16::White },
        high_contrast: Values { rgb: Rgb(255, 255, 255), ansi256: 231, ansi256_rgb: Rgb(255, 255, 255), ansi16: Ansi16::BrightWhite },
    },
    // text.muted
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::DIM,
        normal: Values { rgb: Rgb(138, 138, 138), ansi256: 245, ansi256_rgb: Rgb(138, 138, 138), ansi16: Ansi16::BrightBlack },
        high_contrast: Values { rgb: Rgb(198, 198, 198), ansi256: 251, ansi256_rgb: Rgb(198, 198, 198), ansi16: Ansi16::White },
    },
    // text.inverse
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(0, 0, 0), ansi256: 16, ansi256_rgb: Rgb(0, 0, 0), ansi16: Ansi16::Black },
        high_contrast: Values { rgb: Rgb(0, 0, 0), ansi256: 16, ansi256_rgb: Rgb(0, 0, 0), ansi16: Ansi16::Black },
    },
    // bg.default
    ColorSpec {
        role: Role::Background,
        inherit: true,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(28, 28, 28), ansi256: 234, ansi256_rgb: Rgb(28, 28, 28), ansi16: Ansi16::Black },
        high_contrast: Values { rgb: Rgb(0, 0, 0), ansi256: 16, ansi256_rgb: Rgb(0, 0, 0), ansi16: Ansi16::Black },
    },
    // bg.selected
    ColorSpec {
        role: Role::Background,
        inherit: false,
        no_color: Attrs::REVERSE,
        normal: Values { rgb: Rgb(78, 78, 78), ansi256: 239, ansi256_rgb: Rgb(78, 78, 78), ansi16: Ansi16::BrightBlack },
        high_contrast: Values { rgb: Rgb(11, 61, 145), ansi256: 19, ansi256_rgb: Rgb(0, 0, 175), ansi16: Ansi16::Blue },
    },
    // bg.highlight
    ColorSpec {
        role: Role::Background,
        inherit: false,
        no_color: Attrs::BOLD,
        normal: Values { rgb: Rgb(48, 48, 48), ansi256: 236, ansi256_rgb: Rgb(48, 48, 48), ansi16: Ansi16::Black },
        high_contrast: Values { rgb: Rgb(48, 48, 48), ansi256: 236, ansi256_rgb: Rgb(48, 48, 48), ansi16: Ansi16::Black },
    },
    // accent.default
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::BOLD,
        normal: Values { rgb: Rgb(45, 194, 173), ansi256: 43, ansi256_rgb: Rgb(0, 215, 175), ansi16: Ansi16::Cyan },
        high_contrast: Values { rgb: Rgb(126, 232, 216), ansi256: 116, ansi256_rgb: Rgb(135, 215, 215), ansi16: Ansi16::BrightCyan },
    },
    // focus.default
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::BOLD.union(Attrs::REVERSE),
        normal: Values { rgb: Rgb(255, 224, 102), ansi256: 221, ansi256_rgb: Rgb(255, 215, 95), ansi16: Ansi16::BrightYellow },
        high_contrast: Values { rgb: Rgb(255, 224, 102), ansi256: 221, ansi256_rgb: Rgb(255, 215, 95), ansi16: Ansi16::BrightYellow },
    },
    // status.success
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(63, 185, 80), ansi256: 35, ansi256_rgb: Rgb(0, 175, 95), ansi16: Ansi16::Green },
        high_contrast: Values { rgb: Rgb(126, 231, 135), ansi256: 114, ansi256_rgb: Rgb(135, 215, 135), ansi16: Ansi16::BrightGreen },
    },
    // status.warning
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::BOLD,
        normal: Values { rgb: Rgb(210, 153, 34), ansi256: 172, ansi256_rgb: Rgb(215, 135, 0), ansi16: Ansi16::Yellow },
        high_contrast: Values { rgb: Rgb(255, 224, 102), ansi256: 221, ansi256_rgb: Rgb(255, 215, 95), ansi16: Ansi16::BrightYellow },
    },
    // status.danger
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::BOLD,
        normal: Values { rgb: Rgb(248, 81, 73), ansi256: 203, ansi256_rgb: Rgb(255, 95, 95), ansi16: Ansi16::Red },
        high_contrast: Values { rgb: Rgb(255, 161, 152), ansi256: 217, ansi256_rgb: Rgb(255, 175, 175), ansi16: Ansi16::BrightRed },
    },
    // status.info
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(88, 166, 255), ansi256: 75, ansi256_rgb: Rgb(95, 175, 255), ansi16: Ansi16::Blue },
        high_contrast: Values { rgb: Rgb(165, 214, 255), ansi256: 153, ansi256_rgb: Rgb(175, 215, 255), ansi16: Ansi16::BrightBlue },
    },
    // git.added
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(63, 185, 80), ansi256: 35, ansi256_rgb: Rgb(0, 175, 95), ansi16: Ansi16::Green },
        high_contrast: Values { rgb: Rgb(126, 231, 135), ansi256: 114, ansi256_rgb: Rgb(135, 215, 135), ansi16: Ansi16::BrightGreen },
    },
    // git.removed
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(248, 81, 73), ansi256: 203, ansi256_rgb: Rgb(255, 95, 95), ansi16: Ansi16::Red },
        high_contrast: Values { rgb: Rgb(255, 161, 152), ansi256: 217, ansi256_rgb: Rgb(255, 175, 175), ansi16: Ansi16::BrightRed },
    },
    // git.modified
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(210, 153, 34), ansi256: 172, ansi256_rgb: Rgb(215, 135, 0), ansi16: Ansi16::Yellow },
        high_contrast: Values { rgb: Rgb(255, 224, 102), ansi256: 221, ansi256_rgb: Rgb(255, 215, 95), ansi16: Ansi16::BrightYellow },
    },
    // git.conflict
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::BOLD,
        normal: Values { rgb: Rgb(240, 136, 62), ansi256: 208, ansi256_rgb: Rgb(255, 135, 0), ansi16: Ansi16::Yellow },
        high_contrast: Values { rgb: Rgb(255, 183, 124), ansi256: 216, ansi256_rgb: Rgb(255, 175, 135), ansi16: Ansi16::BrightYellow },
    },
    // git.branch.base
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(188, 140, 255), ansi256: 141, ansi256_rgb: Rgb(175, 135, 255), ansi16: Ansi16::Magenta },
        high_contrast: Values { rgb: Rgb(226, 197, 255), ansi256: 189, ansi256_rgb: Rgb(215, 215, 255), ansi16: Ansi16::BrightMagenta },
    },
    // agent.1
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(230, 159, 0), ansi256: 178, ansi256_rgb: Rgb(215, 175, 0), ansi16: Ansi16::Yellow },
        high_contrast: Values { rgb: Rgb(230, 159, 0), ansi256: 178, ansi256_rgb: Rgb(215, 175, 0), ansi16: Ansi16::Yellow },
    },
    // agent.2
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(86, 180, 233), ansi256: 74, ansi256_rgb: Rgb(95, 175, 215), ansi16: Ansi16::Cyan },
        high_contrast: Values { rgb: Rgb(86, 180, 233), ansi256: 74, ansi256_rgb: Rgb(95, 175, 215), ansi16: Ansi16::Cyan },
    },
    // agent.3
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(0, 158, 115), ansi256: 36, ansi256_rgb: Rgb(0, 175, 135), ansi16: Ansi16::Green },
        high_contrast: Values { rgb: Rgb(0, 158, 115), ansi256: 36, ansi256_rgb: Rgb(0, 175, 135), ansi16: Ansi16::Green },
    },
    // agent.4
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(240, 228, 66), ansi256: 220, ansi256_rgb: Rgb(255, 215, 0), ansi16: Ansi16::BrightYellow },
        high_contrast: Values { rgb: Rgb(240, 228, 66), ansi256: 220, ansi256_rgb: Rgb(255, 215, 0), ansi16: Ansi16::BrightYellow },
    },
    // agent.5
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(79, 163, 224), ansi256: 74, ansi256_rgb: Rgb(95, 175, 215), ansi16: Ansi16::BrightBlue },
        high_contrast: Values { rgb: Rgb(79, 163, 224), ansi256: 74, ansi256_rgb: Rgb(95, 175, 215), ansi16: Ansi16::BrightBlue },
    },
    // agent.6
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(213, 94, 0), ansi256: 166, ansi256_rgb: Rgb(215, 95, 0), ansi16: Ansi16::Red },
        high_contrast: Values { rgb: Rgb(213, 94, 0), ansi256: 166, ansi256_rgb: Rgb(215, 95, 0), ansi16: Ansi16::Red },
    },
    // agent.7
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(204, 121, 167), ansi256: 175, ansi256_rgb: Rgb(215, 135, 175), ansi16: Ansi16::Magenta },
        high_contrast: Values { rgb: Rgb(204, 121, 167), ansi256: 175, ansi256_rgb: Rgb(215, 135, 175), ansi16: Ansi16::Magenta },
    },
    // agent.8
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(255, 255, 255), ansi256: 231, ansi256_rgb: Rgb(255, 255, 255), ansi16: Ansi16::BrightWhite },
        high_contrast: Values { rgb: Rgb(255, 255, 255), ansi256: 231, ansi256_rgb: Rgb(255, 255, 255), ansi16: Ansi16::BrightWhite },
    },
    // agent.state.active
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::NONE,
        normal: Values { rgb: Rgb(63, 185, 80), ansi256: 35, ansi256_rgb: Rgb(0, 175, 95), ansi16: Ansi16::Green },
        high_contrast: Values { rgb: Rgb(126, 231, 135), ansi256: 114, ansi256_rgb: Rgb(135, 215, 135), ansi16: Ansi16::BrightGreen },
    },
    // agent.state.idle
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::DIM,
        normal: Values { rgb: Rgb(138, 138, 138), ansi256: 245, ansi256_rgb: Rgb(138, 138, 138), ansi16: Ansi16::BrightBlack },
        high_contrast: Values { rgb: Rgb(198, 198, 198), ansi256: 251, ansi256_rgb: Rgb(198, 198, 198), ansi16: Ansi16::White },
    },
    // agent.state.done
    ColorSpec {
        role: Role::Foreground,
        inherit: false,
        no_color: Attrs::DIM,
        normal: Values { rgb: Rgb(138, 138, 138), ansi256: 245, ansi256_rgb: Rgb(138, 138, 138), ansi16: Ansi16::BrightBlack },
        high_contrast: Values { rgb: Rgb(198, 198, 198), ansi256: 251, ansi256_rgb: Rgb(198, 198, 198), ansi16: Ansi16::White },
    },
];

/// A symbol token (DSYS-GRP-001 § 2.2).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum SymbolToken {
    /// `success`: Success
    Success,
    /// `error`: Error
    Error,
    /// `warning`: Warning
    Warning,
    /// `info`: Information
    Info,
    /// `agent.active`: Agent active
    AgentActive,
    /// `agent.idle`: Agent idle
    AgentIdle,
    /// `agent.done`: Agent finished
    AgentDone,
    /// `conflict`: Predicted conflict
    Conflict,
    /// `blocked`: Blocked by policy
    Blocked,
    /// `undo`: Snapshot / undo available
    Undo,
}

impl SymbolToken {
    /// Every token, in declaration order.
    pub const ALL: [SymbolToken; 10] = [
        SymbolToken::Success,
        SymbolToken::Error,
        SymbolToken::Warning,
        SymbolToken::Info,
        SymbolToken::AgentActive,
        SymbolToken::AgentIdle,
        SymbolToken::AgentDone,
        SymbolToken::Conflict,
        SymbolToken::Blocked,
        SymbolToken::Undo,
    ];

    /// The token name in `packages/design-tokens`.
    pub const fn name(self) -> &'static str {
        match self {
            SymbolToken::Success => "success",
            SymbolToken::Error => "error",
            SymbolToken::Warning => "warning",
            SymbolToken::Info => "info",
            SymbolToken::AgentActive => "agent.active",
            SymbolToken::AgentIdle => "agent.idle",
            SymbolToken::AgentDone => "agent.done",
            SymbolToken::Conflict => "conflict",
            SymbolToken::Blocked => "blocked",
            SymbolToken::Undo => "undo",
        }
    }

    pub(crate) const fn spec(self) -> &'static SymbolSpec {
        &SYMBOL_SPECS[self as usize]
    }
}

const SYMBOL_SPECS: [SymbolSpec; 10] = [
    // success
    SymbolSpec { glyph: "✔", glyph_width: 1, ascii: "[ok]" },
    // error
    SymbolSpec { glyph: "✖", glyph_width: 1, ascii: "[x]" },
    // warning
    SymbolSpec { glyph: "⚠", glyph_width: 2, ascii: "[!]" },
    // info
    SymbolSpec { glyph: "ℹ", glyph_width: 2, ascii: "[i]" },
    // agent.active
    SymbolSpec { glyph: "●", glyph_width: 1, ascii: "*" },
    // agent.idle
    SymbolSpec { glyph: "◐", glyph_width: 1, ascii: "~" },
    // agent.done
    SymbolSpec { glyph: "○", glyph_width: 1, ascii: "o" },
    // conflict
    SymbolSpec { glyph: "⚡", glyph_width: 2, ascii: "[c]" },
    // blocked
    SymbolSpec { glyph: "⛔", glyph_width: 2, ascii: "[blocked]" },
    // undo
    SymbolSpec { glyph: "⟲", glyph_width: 1, ascii: "[undo]" },
];
