//! Embeds the message catalogs (ADR-GRP-016 § 4): every `i18n/<lang>/<feature>.txt` is
//! registered by its presence, so a story adds its messages in its own file and edits no
//! shared list.

use std::fmt::Write as _;
use std::path::Path;

const LANGS: [&str; 2] = ["en", "es"];

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("i18n");
    // A directory: Cargo reruns when any file in it is added, removed or changed.
    println!("cargo:rerun-if-changed={}", root.display());
    let mut out = String::from("// Generated by build.rs from i18n/<lang>/<feature>.txt.\n");
    for lang in LANGS {
        let dir = root.join(lang);
        let mut files: Vec<_> = std::fs::read_dir(&dir)
            .unwrap_or_else(|err| panic!("{}: {err}", dir.display()))
            .map(|entry| entry.expect("catalog entry").path())
            .filter(|p| p.extension().is_some_and(|e| e == "txt"))
            .collect();
        files.sort();
        writeln!(
            out,
            "pub(crate) const {}: &[(&str, &str)] = &[",
            lang.to_uppercase()
        )
        .unwrap();
        for path in files {
            let feature = path.file_stem().and_then(|s| s.to_str()).expect("utf-8");
            writeln!(
                out,
                "    ({feature:?}, include_str!({:?})),",
                path.display().to_string()
            )
            .unwrap();
        }
        out.push_str("];\n");
    }
    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("i18n_catalogs.rs");
    std::fs::write(dest, out).expect("write the catalog list");
}
